name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image (with VITE_API_URL)
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/corporationy-frontend:latest .

      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/corporationy-frontend:latest

      - name: Generate docker-compose.yml for frontend
        run: |
          cat <<EOF > docker-compose.yml
          version: "3.8"
          services:
            frontend:
              image: ${{ secrets.DOCKER_USERNAME }}/corporationy-frontend:latest
              deploy:
                replicas: 1
                placement:
                  preferences:
                    - spread: docker-node-3
          EOF

      - name: Deploy to Docker Swarm
        run: docker stack deploy -c docker-compose.yml frontend-stack